name: Build static files

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://status.kaisbn.fr
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.deploy_token }}
      - name: Upload submodule artifact
        uses: actions/upload-artifact@v3
        with:
          name: theme-cstate
          path: |
            themes/cstate

  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://status.kaisbn.fr
    container:
      image: registry.gitlab.com/pages/hugo/hugo_extended:0.65.3
    needs: pull
    steps:
      - uses: actions/checkout@v3
      - name: Download submodule
        uses: actions/download-artifact@v3
        with:
          name: theme-cstate
      - name: Build
        run: hugo
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: |
            public
      - name: Download public folder
        uses: actions/download-artifact@v3
        with:
          name: public
      - name: Push changes to gh-pages branch
        run: .github/workflows/push.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.deploy_token }}

